---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: myenv
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/chart-image: glob:master-*
spec:
  releaseName: myenv
  chart:
    git: ssh://git@github.com/avielb/test-flux.git
    ref: master
    path: app
  values:
    env:
      AA: env
      BB: env
    image:
      repository: avielb/test-flux
      tag: master-7895

